language: go

go:
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

install:
  - go get github.com/dchest/uniuri
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/securecookie
  - go get golang.org/x/crypto/bcrypt

script:
- go test -v -covermode=count -coverprofile=coverage.out ./...
- goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
- make

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username ewhal --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
